### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by An-ding-S** [MaterialCleaner/MaterialCleaner#10]
为什么挂载失败？
还有规则的添加？

**Comment by GuhDoy** [comment]
具体描述一下挂载异常的复现步骤？
Cleaner 服务只在自身被启动和应用被启动时执行挂载，而不会“尽最大努力”保证应用已挂载。部分情况下的挂载异常是预期行为（例如在应用运行时删除挂载的文件夹，或者修改挂载规则等）。

使用帮助以后会写在 github wiki，不过短时间内不会写。
另外，下个版本会增加挂载规则制作向导和测试挂载规则功能，以尝试简化编写规则。

**Comment by An-ding-S** [comment]
比如一个软件在没有运行的状态下：
首先添加规则，无论是预设规则还是手动，然后打开此软件。刷新一下页面，就会出现挂载异常。异常标识是（这个软件的进程ID未运行），无论怎样。打开某软件。再关闭，再打开。这个软件的进程ID都会变化。所以才会导致挂载异常。然后重定向失败。


这是我自己理解的。但不知道怎么锁定某个程序的进程ID

**Comment by GuhDoy** [comment]
我好像知道了，zygisk 模块在安卓 12 以前的系统上有点问题😂
你关闭 zygisk 模块试下 logcat 模式能不能用

**Comment by An-ding-S** [comment]
当把它加入配置排除列表时。又无法获取root权限。还是不能用。如下图：
![Screenshot_2022-08-14-22-11-29-128_me.gm.cleaner.jpg](https://user-images.githubusercontent.com/60436881/184541069-52fa56c1-2cf7-4c3b-a946-47a5877dfa3e.jpg)

**Comment by GuhDoy** [comment]
为何要加入排除列表？
