### ISSUE TITLE
[Bug report] 启动服务超时

### ISSUE THREAD

**Issue by gitiy1** [MaterialCleaner/MaterialCleaner#102]
**Describe the bug**
今天打开的时候，发现隔离失效，点击启动按钮，magisk 也显示已获取 root 权限，但过了一会就会返回启动超时，卸载重装，重启毫无作用。

**To Reproduce**
1. 点击启动按钮

**Screenshots**
![Screenshot_20231208-092400_质感清理](https://github.com/MaterialCleaner/MaterialCleaner/assets/91715524/42625056-dbb9-4e47-80ba-2121eb26c99a)
![Screenshot_20231208-092409_质感清理](https://github.com/MaterialCleaner/MaterialCleaner/assets/91715524/7e55372e-33c5-4ead-b0d3-13f880822ec7)

**Running environment (please complete the following information):**
 - Device: Redmi Note 11 5G（evergo)
 - OS: Android 13
 - Cleaner Version 2(1493)
 - Cleaner Hooks Version 1.8.4
 - MPM Version LSPosed

**Logs**
[Cleaner_2_2023年12月8日 09_11_44.log](https://github.com/MaterialCleaner/MaterialCleaner/files/13607875/Cleaner_2_2023.12.8.09_11_44.log)

**Comment by gitiy1** [comment]
[Cleaner_1.10.6_2023年12月8日 09_04_06.log](https://github.com/MaterialCleaner/MaterialCleaner/files/13607936/Cleaner_1.10.6_2023.12.8.09_04_06.log)
还有一份

**Comment by GuhDoy** [comment]
试一下这个有没有问题
[Cleaner_2-release.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/13621526/Cleaner_2-release.zip)

**Comment by gitiy1** [comment]
感谢，这个版本目前可以工作了

**Comment by gitiy1** [comment]
不过还有一个困扰已久的问题，就是有的时候开机会不挂载 /storage/emulated/0，具体表现为文件极客显示空间为 0 kb，用命令查看显示该目录 permission denied，这种情况下得重启才能解决，一般来说我重启后会发现 Zygisk 模块会被禁用，不知道如何提取这个的日志。
