### ISSUE TITLE
[Bug report] 这种使用声音保存文件的如何重定向呢

### ISSUE THREAD

**Issue by xushet** [MaterialCleaner/MaterialCleaner#103]
![Screenshot_20231209-103131_Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/34502902/4906546c-4fdd-45d9-b0d7-53edb16146cd)

![Screenshot_20231209-103320_Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/34502902/73f4c9d0-1807-4188-83d5-6542ef0cc95c)

比如虎扑保存的视频

**Comment by Webpage-gh** [comment]
可以试试[媒体存储设备管理](https://github.com/MaterialCleaner/Media-Provider-Manager/releases/latest)。在LSPosed激活推荐作用域后按模块提示继续操作如重启手机，在模块内为虎扑创建插入挂钩，在允许的媒体类型中取消勾选视频，即时生效
希望能帮到你

**Comment by xushet** [comment]
> 可以试试[媒体存储设备管理](https://github.com/MaterialCleaner/Media-Provider-Manager/releases/latest)。在LSPosed激活推荐作用域后按模块提示继续操作如重启手机，在模块内为虎扑创建插入挂钩，在允许的媒体类型中取消勾选视频，即时生效
> 希望能帮到你

还是没有效果

**Comment by Webpage-gh** [comment]
我当时忽略了一点，创建这个文件的应用可能不是虎扑。请打开媒体存储设备管理中的使用记录，以便找到是哪个应用创建了文件

**Comment by GuhDoy** [comment]
这竟然是在反馈bug？
