### ISSUE TITLE
[Bug report] 作用域到底是什么？

### ISSUE THREAD

**Issue by fsxitutu** [MaterialCleaner/MaterialCleaner#104]
google play版本2，已安装对应zygisk模块和在lsp勾选媒体存储设备(推荐作用域)
app内一直提示请在lsposed中激活质感清理并重启系统，重启后问题依旧。
且无法使用储存重定向功能，编写的规则在退出重新进入app后会显示已启用0条规则(规则无法保存？)

本机环境
设备：pixel 7 pro
系统：los 20(安卓13)
lsp：1.8.4(6609)-zygisk
质感清理：2(模块和服务版本为1494)

如何还需要什么信息请提出，我尽力补充

**Comment by Webpage-gh** [comment]
你好，作用域就是`com.google.android.providers.media.module`。如果有可能的话，请尝试备份软件数据，更新质感清理及其模块到最新版本并重启手机再试一次

**Comment by fsxitutu** [comment]
> 你好，作用域就是`com.google.android.providers.media.module`。如果有可能的话，请尝试备份软件数据，更新质感清理及其模块到最新版本并重启手机再试一次

模块及质感清理就是最新版本

**Comment by Webpage-gh** [comment]
那就等原作者回复吧。我只能帮到这了2023年12月11日 下午3:10，fsxitutu ***@***.***>写道：

你好，作用域就是com.google.android.providers.media.module。如果有可能的话，请尝试备份软件数据，更新质感清理及其模块到最新版本并重启手机再试一次

模块及质感清理就是最新版本

**Comment by GuhDoy** [comment]
这个问题最新版应该已经在应用内有清晰的提示了
