### ISSUE TITLE
[Bug report] app异常崩溃

### ISSUE THREAD

**Issue by sssssttttttjs** [MaterialCleaner/MaterialCleaner#112]
**Describe the bug**
app异常崩溃

**To Reproduce**
1. 在启动器打开app
2. 等一秒
3. 崩溃

**Screenshots**

**Running environment (please complete the following information):**
 - Device: Xiaomi Mi 10 pro
 - OS: pixelexperience plus 13 unoffical
 - Cleaner Version: 2
 - Cleaner Hooks Version:1.8.4

**Logs**
[me.gm.cleaner_2023-12-23T21_08_08.143.log](https://github.com/MaterialCleaner/MaterialCleaner/files/13759193/me.gm.cleaner_2023-12-23T21_08_08.143.log)
[me.gm.cleaner_2023-12-23T21_09_02.356.log](https://github.com/MaterialCleaner/MaterialCleaner/files/13759194/me.gm.cleaner_2023-12-23T21_09_02.356.log)
[me.gm.cleaner_2023-12-23T21_32_57.782.log](https://github.com/MaterialCleaner/MaterialCleaner/files/13759196/me.gm.cleaner_2023-12-23T21_32_57.782.log)

**Additional context**
打开后即使不进行任何操作也会崩溃
如果进入了一个二级页面如“服务设置”，那么崩溃时会回到主页面，也算是能正常用了
试着重启了两次，一次什么也不做，一次删除了最近安装的模块，依然没有效果

**Comment by GuhDoy** [comment]
包好，包好！这样的趁热吃下。这样的人血馒头，什么痨病都包好！
