### ISSUE TITLE
[Bug report] Android 14 无法使用文件系统记录

### ISSUE THREAD

**Issue by etjec4** [MaterialCleaner/MaterialCleaner#113]
**Describe the bug**
模块 1.9.1，LSPOSED已激活。
但开启时一直提示 此功能需要……

**Comment by unclefive55** [comment]
同，快疯了

**Comment by unclefive55** [comment]
> **Describe the bug**
> 模块 1.9.1，LSPOSED已激活。
> 但开启时一直提示 此功能需要……
> 
> 

找到解决办法了，用1.8.4版本的zygisk模块
