### ISSUE TITLE
[服务环境异常] 

### ISSUE THREAD

**Issue by Mubai-meng** [MaterialCleaner/MaterialCleaner#114]
**重定向服务总是自动关闭，提示服务环境异常**

**Screenshots**
![Screenshot_2023-12-29-16-37-23-911_me.gm.cleaner.jpg](https://github.com/MaterialCleaner/MaterialCleaner/assets/86759349/de8e7b4f-fe8d-432e-be0c-c27dc2344b58)

**Running environment**
 - Device: [小米12s]
 - OS: [Android 14]
 - Cleaner Version [2.0.2]
 - Cleaner Hooks Version [1.9.1]

**Logs**
![log.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/13792239/log.zip)

**Comment by GuhDoy** [comment]
存储重定向功能有着复杂的基础实现，同时需要复杂的逻辑才能降低使用难度和简化操作，我们为开发此功能已巨额亏损，如有能力还望付费支持。您也可以选择停止使用此功能，我们便不会再打扰您。
