### ISSUE TITLE
[Bug report] 模块的logs文件夹会生成巨型日志文件

### ISSUE THREAD

**Issue by 20171213** [MaterialCleaner/MaterialCleaner#115]
![Screenshot_20240102-223145_crDroid Home](https://github.com/MaterialCleaner/MaterialCleaner/assets/34502902/4cb38a78-d3e4-463f-a618-08be74c98cee)
这个是bug吗

**Comment by GuhDoy** [comment]
把自动抓取开关机日志并自动救砖关掉，这个选项在新版本改成默认关闭了

**Comment by 20171213** [comment]
> 把自动抓取开关机日志并自动救砖关掉，这个选项在新版本改成默认关闭了

好的
