### ISSUE TITLE
[Bug report] 直接把王者数据包删了

### ISSUE THREAD

**Issue by gitG0hub** [MaterialCleaner/MaterialCleaner#121]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Running environment (please complete the following information):**
 - Device: [e.g. Pixel 6]
 - OS: [e.g. Android 8.1]
 - Cleaner Version [e.g. 1.6]
 - Cleaner Hooks Version [e.g. Not Installed/1.4]

**Logs**
Logs are a must if the bug is not reproducible on all my running environments! If you don't provide logs in this case, the issue will be closed.

**Additional context**

**Comment by GuhDoy** [comment]
我确实正打算进行一些行为调整，有可能顺便解决这个问题。另外，如果可以，能否提供王者数据包的路径呢？

**Comment by gitG0hub** [comment]
目前只发现王者会，有可能是他把一部分文件直接放到cache文件夹![Screenshot_20240415-141722.png](https://github.com/MaterialCleaner/MaterialCleaner/assets/65051091/7eddee89-6cbd-492c-830a-3275200f883b)

**Comment by gitG0hub** [comment]
软件是很好的软件，也是在酷安莫名看到有人截图里有这个，爱玩机里也有cleanerhook模块，再加上用过以前好用的像清浊类的，但是这部安卓11貌似只能用存储重定向选取文件夹，体验很差，而这款就很好，会一直用的

**Comment by gitG0hub** [comment]
如果有时间的话，我也提点小建议，就这个问题而言，可以添加白名单这个功能，方便选取应用。再有就是或许可以添加自动化，如定时定类，这样我认为这款软件可能变成目前功能最强大的专业开源扫描应用了

**Comment by gitG0hub** [comment]
目前已经排除相关目录
