### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MrMoxing** [MaterialCleaner/MaterialCleaner#14]
The lite record seems to be broken, deleting it doesn't work

**Comment by GuhDoy** [comment]
Really? I have no problem using it. Can you describe it more clearly?

**Comment by MrMoxing** [comment]
https://user-images.githubusercontent.com/81543605/191624501-c11511be-5f0e-401a-8631-f21249a0dc68.mp4

I click on it and it can't delete the record properly

**Comment by GuhDoy** [comment]
Manually delete the database files (at /data/user_de/0/me.gm.cleaner/databases), then restart the Cleaner service.  Wait for a record later and then try if you can delete them with "Downsize records"?

Or if you can use logcat to grab logs, can you take a look at what errors are reported when you click "Downsize records"?

**Comment by GuhDoy** [comment]
Fixed.
