### ISSUE TITLE
Android9 设备出现「服务环境异常」与经常性的挂载失败

### ISSUE THREAD

**Issue by MisaLiu** [MaterialCleaner/MaterialCleaner#15]
* 系统版本：MIUI 12 20.6.18
* 安卓版本：9
* Magisk 版本：v25.2(25200)
* Cleaner 版本：1.9.2

## 问题描述
启动服务时主界面不会出现任何异常提示，但在退出应用重进后则会提示 `「服务环境异常」5872: 没有活动管理器日志，存储重定向不会生效（如果刚启动服务请忽略）`

同时，根据反复测试的结果，软件挂载也容易出现问题：

* 当在启动服务后启动应用时，应用的所有进程均挂载失败
* 当在启动应用后启动服务时，在启动服务前的所有应用进程均可被挂载，但无法挂载应用在启动服务之后新增的进程

**Comment by GuhDoy** [comment]
安卓9不在适配范围内（
