### ISSUE TITLE
文案描述问题

### ISSUE THREAD

**Issue by xiangyu0** [MaterialCleaner/MaterialCleaner#17]
说实话这个挂载的文案描述是不是有些歧义，文案的意思像是将来源中的文件挂载到目标的路径中，但实际上写规则时是把目标中的文件挂载到来源中的路径，能否修改一下？
![Screenshot_2022-09-30-20-01-52-581_me gm cleaner](https://user-images.githubusercontent.com/104448526/193265556-6e12f74b-43ec-4d55-a3a6-908e67018087.jpg)

**Comment by GuhDoy** [comment]
这是根据 [Linux manual page](https://man7.org/linux/man-pages/man2/mount.2.html) 的介绍翻译的。

**Comment by GuhDoy** [comment]
已经有测试挂载规则了
