### ISSUE TITLE
功能异常反馈

### ISSUE THREAD

**Issue by znz722** [MaterialCleaner/MaterialCleaner#22]
软件1.8~最新1.93版本 服务开启微信存储重定向后，显示已挂载，但出现 “储存卡已拔出.....朋友圈功能暂不可用”提示，朋友圈图片无法打开。
软件1.70版本相同设置并无异常，微信储存功能正常，1.71版本开始服务启动失败（1.80~1.93无服务启动失败问题）
![IMG_20221008_192135](https://user-images.githubusercontent.com/73382331/194705311-f04a7547-22b1-41b2-b960-9a97c5ce4f8b.jpg)
![Screenshot_2022-10-08-19-18-34-578_me gm cleaner](https://user-images.githubusercontent.com/73382331/194705324-d64abcdc-c1fd-4d5e-9e62-8b9e6ee7ee9f.jpg)
存储问题同同时复现于Tim，开启重定向后Tim版QQ联系人头像也无法加载，关闭重定向后可回复。
设备信息小米11PRO 安卓12 已逐一版本测试

**Comment by znz722** [comment]
第一张图为1.93版本，第二张图为1.70版本，挂载规则相同，1.93出现储存异常提示。
软件1.8至1.93版本 服务开启微信存储重定向后，显示已挂载，但出现 “储存卡已拔出.....朋友圈功能暂不可用”提示，朋友圈图片无法打开。
软件1.70版本相同设置并无异常，微信储存功能正常，1.71版本开始服务启动失败（1.80至1.93无服务启动失败问题）

**Comment by GuhDoy** [comment]
我这里没有这个问题，你可以尝试手动设置一下 /storage/emulated/0/Android/data/com.tencent.mm 及其子文件的所有者为微信。
如果你使用 CleanerHooks 模块，请确认是否为最新版本 755。753 测试版是会导致你说的这个问题的。
对于开机无法自动启动服务问题，请检查是否在系统设置（以及其它管理运行的应用）中允许了 Cleaner 自启动。

**Comment by znz722** [comment]
软件1.93，模块版本755，添加隔离规则挂载没问题，显示进程也全部进去了，但是还是显示储存卡已拔出，读取出了问题，Tim也是一样，应该是同个原因。想请问一下怎么设置文件夹及子文件的所有者
![IMG_20221009_001915](https://user-images.githubusercontent.com/73382331/194717324-3fbe968a-02db-4b92-b40b-c2e4ee6a880a.jpg)

**Comment by znz722** [comment]
设置了允许读取外部相册也显示储存卡已拔出打不开，表情包也发不了
![Screenshot_2022-10-09-00-31-35-973_me gm cleaner](https://user-images.githubusercontent.com/73382331/194717788-28de5c2f-1df5-4bba-8b65-e593b2d25cf4.jpg)
![IMG_20221009_003109](https://user-images.githubusercontent.com/73382331/194717792-f3c8fad6-9ec4-4c0b-bcf9-017e71b6a9d4.jpg)

**Comment by znz722** [comment]
解决了，默认重定向到cache会发生存储错误，重定向到上一级大文件就没问题了，Tim也是一样解决（=´口｀=）
![IMG_20221009_005758](https://user-images.githubusercontent.com/73382331/194718897-0c7ea99e-be30-419e-a73f-58342df39851.jpg)
