### ISSUE TITLE
类原生安卓12安装模块后会导致zygisk不生效

### ISSUE THREAD

**Issue by dmyn1993** [MaterialCleaner/MaterialCleaner#23]
类原生安卓12安装模块后会导致zygisk不生效，magisk提示zygisk未启用，但magisk的设置里实际上已经启用了zygisk，重启后依旧如此，卸载模块后正常

**Comment by GuhDoy** [comment]
需要开机日志

**Comment by guoyanhuyun** [comment]
相同问题，机子是pixel 5, Android 13

**Comment by GuhDoy** [comment]
> 相同问题，机子是pixel 5, Android 13![Screenshot_20221014-000659.png](https://user-images.githubusercontent.com/54035040/195649042-2a6e8bfc-5454-481a-8a16-ce62aa28b814.png)![Screenshot_20221014-000706.png](https://user-images.githubusercontent.com/54035040/195649078-5833c868-9d96-4473-a1e7-024a4c5916ec.png)![Screenshot_20221014-000656.png](https://user-images.githubusercontent.com/54035040/195649104-b337629b-1d49-436c-b88d-ab7e0109dde9.png)

好的，我用avd测试一下

**Comment by GuhDoy** [comment]
![image](https://user-images.githubusercontent.com/46047320/198244596-caaaec6a-aa3d-4896-aa4b-fb447e511b18.png)
已经在 avd 测试正常运行，如有问题请附上开机日志
