### ISSUE TITLE
大量文件系统记录导致 ANR、OOM

### ISSUE THREAD

**Issue by jiesou** [MaterialCleaner/MaterialCleaner#25]
如题，少量的时候还好只是卡一下，长期使用后大量的记录会导致 Cleaner 应用直接无响应，那个“精简记录”的按钮也点不出。甚至导致设备软重启
而且可能是因为文件系统记录部分是在 Hook 模块中实现的，即使强制把应用程序关了，内存占用也还会狂飙。且清除应用数据没法清除记录

应用版本: 1.9.4
服务版本：791
Zygisk 模块版本：755

**Comment by GuhDoy** [comment]
我不认为会出现这个问题。
Hook 模块只负责把监测到的记录发送给 Cleaner 服务，自身不保存任何记录；Cleaner 服务收到数据后判断要不要保存，要保存则交给 room 保存到数据库，否则舍弃，同样不会占用大量内存。
对于界面，一般加载 100 条记录，如果这 100 条记录都来自同一个应用则再加载 100 条，直到有不同应用的或者加载完所有记录为止。所以如果有大量来自同一个应用的数据可能会加载较长时间，但是由于是异步加载也不可能出现 ANR。

**Comment by jiesou** [comment]
就是加载界面时占用大量内存，关闭应用也没用，只能强制重启
还有存储到的数据库是在哪，现在删也删不掉

**Comment by jiesou** [comment]
https://user-images.githubusercontent.com/84175239/198866119-04a57d77-1e84-42a2-86f5-3d857affb506.mp4

能复现

github 大小限制 10m 压的比较糊

**Comment by GuhDoy** [comment]
数据库在 /data/user_de/0/me.gm.cleaner/databases，删除之后要重启服务

**Comment by jiesou** [comment]
![Screenshot_2022-10-30-21-39-38-016_bin.mt.plus.png](https://user-images.githubusercontent.com/84175239/198881630-a185fbe9-0c41-4a63-aa6b-f7eda917d026.png)

有点离谱。 。之后肯定要做过期记录自动删除之类的吧

**Comment by GuhDoy** [comment]
过期删除我也考虑过，但我觉得不太合适，因为文件系统记录的时效可能会比较长。我想到的方案是如果数据库文件太大就不自动加载，而是显示一个提示。
关于录屏里的 ANR，我想是点精简记录导致的，因为这个对话框里面的记录数量是在主线程加载的，你点击的时候应该是记录列表的 cursor 还没返回，导致查询记录数量的事务被阻塞了很长时间。

**Comment by jiesou** [comment]
最好肯定是提供过期或过量删除的选项，然后界面能分页展示

**Comment by GuhDoy** [comment]
1.9.5 版本在数据库大于 1GB 时将不会自动加载记录
