### ISSUE TITLE
类原生安卓12安装模块后会导致zygisk不生效

### ISSUE THREAD

**Issue by Glospred** [MaterialCleaner/MaterialCleaner#26]
之前知道这个模块尝试后遇到了同样问题，发现已有issue故等待解决，没想到无法复现，故带来了日志中装上模块重启后的部分
[magisk.log](https://github.com/MaterialCleaner/MaterialCleaner/files/9895624/magisk.log)

**Comment by GuhDoy** [comment]
magisk日志没用（

**Comment by Glospred** [comment]
草，抱歉，请问需要的日志在哪？

**Comment by GuhDoy** [comment]
[Log.Catcher-v21.21.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/9900504/Log.Catcher-v21.21.zip)

**Comment by Glospred** [comment]
[boot.log](https://github.com/MaterialCleaner/MaterialCleaner/files/9900749/boot.log)

**Comment by GuhDoy** [comment]
没有模块加载的信息
![Screenshot_20221031-235222_MT管理器](https://user-images.githubusercontent.com/46047320/199051819-6046a2b9-79d7-444f-8d6e-3b75269522af.png)
这是我刚才自己抓的日志，一般错误信息应该在 Initializing Cleaner Hooks vXXX 之后，如果出现 Cleaner Hooks vXXX initialized 就是加载成功了。

**Comment by Glospred** [comment]
> 出现

那请问有没有zygisk加载的信息呢？因为问题是打开模块后会导致zygisk不启用
另外模块如果安装但不打开不会导致这个问题，打开后就会出现

**Comment by GuhDoy** [comment]
把zygisk打开了再重启

**Comment by Glospred** [comment]
zygisk一直是打开的，是打开了模块后，会导致zygisk在开机过程中启动失败，模块不会导致zygisk的开关被关掉
另外请问我获取日志的方式是不是有问题？我是在打开模块后重启，然后运行脚本获取log

**Comment by GuhDoy** [comment]
那个 log catcher 模块会自动把日志复制到 Download 文件夹的

**Comment by Glospred** [comment]
> 那个 log catcher 模块会自动把日志复制到 Download 文件夹的。
> 还有 Cleaner Hooks 的开关也一定要打开，我需要的是运行出错的信息，不开模块的话我看什么呢？

问题是，开了模块导致了zygisk无法启动，或许是和别的模块的冲突，但结果是模块确实没有日志信息，如果不能通过比较打开和不打开模块情况下的zygisk运行信息去判断问题所在，那问题确实难以解决

**Comment by GuhDoy** [comment]
你后面发的那个日志不完整，dmesg不是从0开始，也没看到 "welcome to lsposed"

**Comment by GuhDoy** [comment]
而且只要加载了Cleaner Hooks模块，Initializing Cleaner Hooks vXXX 信息是必定会有的，没有就说明模块根本没加载

**Comment by Glospred** [comment]
问题出在我对logcatch模块的使用上，对此我表示抱歉，我曾以为这是在MT管理器中运行的sh脚本
这是新的日志文件，里边包含了您需要的部分
[bootlog-2022-11-01-17-14-32.tar.gz](https://github.com/MaterialCleaner/MaterialCleaner/files/9908529/bootlog-2022-11-01-17-14-32.tar.gz)
感谢您的付出

**Comment by GuhDoy** [comment]
发下 /apex/com.android.art/lib64/libart.so

**Comment by Glospred** [comment]
[libart.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/9909319/libart.zip)

**Comment by GuhDoy** [comment]
试试这个 
[zygisk_cleanerhooks_v0.8.2-release.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/9920219/zygisk_cleanerhooks_v0.8.2-release.zip)

**Comment by Glospred** [comment]
感谢，这个确实不会导致zygisk失效了
