### ISSUE TITLE
重定向bug

### ISSUE THREAD

**Issue by Rarlya1** [MaterialCleaner/MaterialCleaner#30]
图片重定向后无法被app正常使用
![IMG_20221123_203051](https://user-images.githubusercontent.com/118902587/203548139-542451ed-670b-47ab-83c2-eeb845e55439.jpg)
![IMG_20221123_203106](https://user-images.githubusercontent.com/118902587/203548164-0434677f-578b-4c85-b22f-043864163bef.jpg)
在app内置的图片选择界面无法选择重定向后的图片
![IMG_20221123_203136](https://user-images.githubusercontent.com/118902587/203548351-b3186ddc-6de5-4ffc-9433-b6e38ef34bf3.jpg)
而系统内置内置相册和app内文件管理可以正常使用重定向后的图片
![IMG_20221123_203209](https://user-images.githubusercontent.com/118902587/203548546-9049e825-8fa4-4bfa-b891-d3d7b37a9734.jpg)
![IMG_20221123_203359](https://user-images.githubusercontent.com/118902587/203548569-405fee0f-eaf0-4dfe-bf61-bf87fe88b16b.jpg)

**Comment by Rarlya1** [comment]
系统是安卓12，在cleaner1.9.2及以上版本必定复现，重启后才可使用重定向后的图片。而1.9.1重启手机后可以维持大约20小时不出现这个bug

**Comment by GuhDoy** [comment]
安装旁边那个模块，打开这个功能
![Screenshot_20221123-231624_媒体存储设备管理.png](https://user-images.githubusercontent.com/46047320/203582369-48488429-ab56-4394-aa88-a012a8f9df93.png)

**Comment by Rarlya1** [comment]
解决了，感谢
