### ISSUE TITLE
谷歌录音机 应用发生频繁闪退

### ISSUE THREAD

**Issue by xdun** [MaterialCleaner/MaterialCleaner#31]
### 遇到的问题

在启用 zygisk_cleanerhooks version=v0.8 versionCode=755 模块后，
会使包名为 com.google.android.apps.recorder 的 谷歌录音机 应用发生频繁闪退
依赖so文件路径错误
使用时我没有添加对该应用的路径规则
停用Magisk模块后问题消失，应用恢复正常

LOG Generated by Magisk
===============
[ 2022-11-30T11:50:03.182        0:  2263:  2263 W/Magisk          ] xhook: repeated map info when create: 7324d4d000-7324d96000 r--p 00000000 fd:02 2209 /system/lib64/libc++.so
[ 2022-11-30T11:50:03.183        0:  2263:  2263 W/Magisk          ] xhook: repeated map info when create: 732dc81000-732dc93000 r--p 00000000 fd:02 2184 /system/lib64/libbase.so

LOG Generated by AppErrorsTracking
===============
.
[Device Brand]: Redmi
[Device Model]: M2012K11C
[Display]: TD1A.221105.001
[Android Version]: 13
[API Version]: 33
[System Locale]: en_US
[Package Name]: com.google.android.apps.recorder
[Error Type]: Native
[Crash Time]: 2022-11-30T11:56:02.144
[Stack Trace]:
Build fingerprint: 'Redmi/haydn/haydn:12/SKQ1.211001.001/V13.0.6.0.SKKCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-11-30 11:56:01.902532205+0800
Process uptime: 2s
Cmdline: com.google.android.apps.recorder
pid: 14169, tid: 14169, name: d.apps.recorder  >>> com.google.android.apps.recorder <<<
uid: 10099
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'Pointer tag for 0xf8dbb87059b3a3b5 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.'
    x0  0000000000000000  x1  0000000000003759  x2  0000000000000006  x3  0000007fe8d51ec0
    x4  0000000000008080  x5  0000000000008080  x6  0000000000008080  x7  8080000000000000
    x8  00000000000000f0  x9  0000007315b6ca30  x10 0000000000000001  x11 0000007315baaee4
    x12 0101010101010101  x13 00000001c5377960  x14 0030feb8f6029c00  x15 0000000000000078
    x16 0000007315c10d60  x17 0000007315bee120  x18 0000007337bce000  x19 0000000000003759
    x20 0000000000003759  x21 00000000ffffffff  x22 070d99755e727700  x23 00000000dd6d7e19
    x24 000000005e67fa3b  x25 00000000ffffd811  x26 00000000898ad240  x27 0000000000000807
    x28 0000007fe8d52160  x29 0000007fe8d51f40
    lr  0000007315b9ca68  sp  0000007fe8d51ea0  pc  0000007315b9ca94  pst 0000000000001000
backtrace:
      #00 pc 0000000000051a94  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 7bacb1a59c1d1e15ca33e05bf3aef78e)
      #01 pc 000000000003df20  /apex/com.android.runtime/lib64/bionic/libc.so (free+96) (BuildId: 7bacb1a59c1d1e15ca33e05bf3aef78e)
      #02 pc 000000000003a9e0  /data/app/~~xlI9qryB4Sww9zm--cHtpA==/com.google.android.apps.recorder-_Wacd6CgXYxkwJ6k3ipPZA==/lib/arm64/libpairipcore.so

**Comment by GuhDoy** [comment]
感谢反馈，这个问题可以把录音机应用加入隐藏列表来临时解决

**Comment by xdun** [comment]
好的。
