### ISSUE TITLE
筛选应用时被排除在外的应用安装状态判断异常

### ISSUE THREAD

**Issue by cnoim** [MaterialCleaner/MaterialCleaner#37]
1.9.5最新版本
当设置了筛选条件导致被隔离的应用排除在应用列表内时，会导致应用判断该应用被卸载，从而弹出清除规则的对话框。
附截图：
![091ad9a0f91556ea61c01c67284f515](https://user-images.githubusercontent.com/52961523/212057779-37b69d17-7ad6-4c63-be16-371e0c379243.jpg)
![4c8b1e68504627ad4059059277ee1ce](https://user-images.githubusercontent.com/52961523/212057797-b33bd8e5-79d4-424e-bce1-0a3a5d8e795d.jpg)
![a770a48242de70d4c88c552aacd31cc](https://user-images.githubusercontent.com/52961523/212058146-6c12d78c-1704-4f7e-87c4-064b4ce806b4.jpg)

**Comment by GuhDoy** [comment]
感谢反馈

**Comment by GuhDoy** [comment]
此问题已于 1.9.6 版本修复
