### ISSUE TITLE
新版本闪退

### ISSUE THREAD

**Issue by HZYint** [MaterialCleaner/MaterialCleaner#4]
1.7.7版本还可以使用，升级后闪退
          ——K30PRO MIUI12.5.7

**Comment by GuhDoy** [comment]
/data/user/0/me.gm.cleaner/files/log 中有日志吗

**Comment by HZYint** [comment]
![Screenshot_2022-02-15-12-29-59-788_bin mt plus](https://user-images.githubusercontent.com/79033942/153992820-b924b831-3572-4672-a86e-8659ee4965b7.jpg)
好像没有

**Comment by GuhDoy** [comment]
那应该没闪退（
也许跟 #2 是同一个问题

**Comment by HZYint** [comment]
可能吧，像是强制退出，MIUI都能有完整的退出动画可能不是闪退😂
