### ISSUE TITLE
添加新的google邮箱账户后，经常性地停止服务

### ISSUE THREAD

**Issue by ONE223** [MaterialCleaner/MaterialCleaner#43]
设备：pixel5 
系统：android11
注册添加了一个新的google的gmail账号，注册添加进gmail后cleaner便停止服务，多次尝试重启服务也都是失败。重启手机后恢复，但是比以往更容易掉服务。
目前发现手机拥有两个google账户之后，cleaner掉服务比以往更严重了且有几率服务无法重启。
卸载重装装了1.95,19.6,1.97版本均有这样的问题。
之前反馈过zygisk模块会导致pixel相机和相册不能用，所以没有测试。

**Comment by GuhDoy** [comment]
需要日志

**Comment by ONE223** [comment]
Cleaner内没有找到导出日志的选项，需要在哪里找到日志？

**Comment by GuhDoy** [comment]
启动服务失败不会弹出超时对话框吗？

**Comment by ONE223** [comment]
没有，没有弹出超时或需要等待。就是秒失败。2023年2月3日 07:04，GuhDoy ***@***.***>写道：

启动服务失败不会弹出超时对话框吗？

**Comment by GuhDoy** [comment]
能否更详细地描述什么叫秒失败？应用程序崩溃了吗？
![Screenshot_2023-02-03-17-47-59-063_me gm cleaner](https://user-images.githubusercontent.com/46047320/216568511-3946eafd-a705-4da2-97f6-e1db80a86c38.jpg)
超时对话框就是为了收集启动失败的日志的机制，它会在开始启动服务的3秒后检查服务是否启动成功（收到服务的binder），如果失败就会弹出来。
如果超时对话框不能正常工作，你可能需要使用更复杂的方式抓取日志。

**Comment by GuhDoy** [comment]
安装这个安装包
[Cleaner_1.10-debug-release.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/10609820/Cleaner_1.10-debug-release.zip)
并重启服务，等到服务崩溃后看看 /data/user/0/me.gm.cleaner/files/tombstones 里有没有日志；另外也可在 /data/tombstones 里找找有没有 内容 包含“cleaner_server”的日志文件。
服务那里红有多种可能，显示的错误信息是什么？

**Comment by GuhDoy** [comment]
由于无回应关闭
