### ISSUE TITLE
关于SDK API 兼容性的问题

### ISSUE THREAD

**Issue by scnjdx108** [MaterialCleaner/MaterialCleaner#45]
Cleaner 在安卓9上无法正常使用，在设置规则点击部分应用时会出现未响应卡死状态，!

zygisk module模块能否支持低至Android P 系统版本？

**Comment by GuhDoy** [comment]
[zygisk_cleanerhooks_v1.2-release.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/10909869/zygisk_cleanerhooks_v1.2-release.zip)
我编译了一个安卓9可以安装的你试一下

**Comment by scnjdx108** [comment]
> [zygisk_cleanerhooks_v1.2-release.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/10909869/zygisk_cleanerhooks_v1.2-release.zip)
> 我编译了一个安卓9可以安装的你试一下

Ok  一会儿测试一下

**Comment by scnjdx108** [comment]
> [zygisk_cleanerhooks_v1.2-release.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/10909869/zygisk_cleanerhooks_v1.2-release.zip)
> 我编译了一个安卓9可以安装的你试一下

我刚已经测试了……模块可以正常使用了，但是 服务设置 功能里面点击部分应用还是会卡死，比如 服务设置 存储从定向 点击 QQ 12321 就会触发无响应状态！

**Comment by GuhDoy** [comment]
点击无响应之后，/data/user/0/me.gm.cleaner/files/log 中是否有文件？如果有请打包传上来

**Comment by scnjdx108** [comment]
> 点击无响应之后，/data/user/0/me.gm.cleaner/files/log 中是否有文件？如果有请打包传上来

查看了……没有生成log![Screenshot_2023-03-10-19-28-16-346_bin.mt.vip.clone.jpg](https://user-images.githubusercontent.com/41535838/224307842-2b433fc5-a2f9-415d-9903-751c9a451532.jpg)

**Comment by GuhDoy** [comment]
感觉需要搭建环境比较麻烦，而且我猜测问题出在获取appops（我对这块不熟），放弃了
