### ISSUE TITLE
Hook模块1.20版本仍然导致录音机和相机无法使用

### ISSUE THREAD

**Issue by ONE223** [MaterialCleaner/MaterialCleaner#47]
设备pixel5，android11。
Hook模块版本：1.20
问题：google默认相机和录音机仍然闪退，按照已关闭的issues31提供的方法，在cleaner内开启隐藏重启仍然闪退。 #

> #

**Comment by ONE223** [comment]
解决了，通过酷安的帖子，发现自己操作错误了隐藏方法有问题

**Comment by GuhDoy** [comment]
需要崩溃日志，否则无法解决

**Comment by GuhDoy** [comment]
如果没有日志请勿再提此问题，否则你会被ban
