### ISSUE TITLE
重定向使用前缀匹配

### ISSUE THREAD

**Issue by LovesAsuna** [MaterialCleaner/MaterialCleaner#48]
由于重定向使用前匹配，因此会出现很尴尬的情况。只要设置了根目录的重定向规则，任何访问私有目录的请求都会被重定向到私有目录内部的前缀。
拿qq为例，假设规则是`/storage/emulated/0 -> /storage/emulated/0/Android/data/com.tecent.mobileqq/cache`，
那qq访问私有目录`/storage/emulated/0/Android/data/com.tecent.mobileqq`的请求就会被重定向到`/storage/emulated/0/Android/data/com.tecent.mobileqq/cache/Android/data/com.tecent.mobileqq/cache`
其结果就是造成了目录的多层嵌套

**Comment by LovesAsuna** [comment]
就是在两行的情况下私有目录也会创建出Android/data/xxx

**Comment by GuhDoy** [comment]
这是VFS的机制，内层空文件夹的路径是挂载点，当查找到这个路径时发现是挂载点于是会跳转文件系统（也就是外层文件夹）。挂载点是路径的成员，如果把内层的空文件夹删除，则对应路径被invalidate，挂载点也会消失。

**Comment by GuhDoy** [comment]
换言之，内层空文件夹必须存在，否则存储重定向失效。

**Comment by LovesAsuna** [comment]
没有办法，使得应用看到的挂载点视图就是想让其看到的，而不需要内层的空文件夹？
