### ISSUE TITLE
点击帮助无法跳转浏览器

### ISSUE THREAD

**Issue by Mubai-meng** [MaterialCleaner/MaterialCleaner#49]
小米
MIUI14
Android13
点击帮助再点击跳转到的APP无任何反应
无论是自带浏览器还是第三方浏览器
测试其他应用相互之间可以跳转

**Comment by GuhDoy** [comment]
无法复现

**Comment by Mubai-meng** [comment]
> 无法复现

新发现，可以跳转到guthub和电子邮件，确实难以复现，并且不是闪退问题不清楚怎么抓相关日志，算了小问题放那吧
