### ISSUE TITLE
貌似有一些硬伤

### ISSUE THREAD

**Issue by Mubai-meng** [MaterialCleaner/MaterialCleaner#51]
比如我想让微信可以读取download文件夹的文件，但是不让它在download文件夹下面创建文件，两个规则会互相冲突

规则如下：
![IMG_20230321_154459.jpg](https://user-images.githubusercontent.com/86759349/226544556-c80a1f3e-e84d-449f-81aa-80d9fda266a0.jpg)

**Comment by GuhDoy** [comment]
可你写的规则的意思是既想让微信读 Download 文件夹又不想让微信读 Download 文件夹

**Comment by Mubai-meng** [comment]
> 可你写的规则的意思是既想让微信读 Download 文件夹又不想让微信读 Download 文件夹

可是怎么怎么写才能让它只读download而不能写download呢，以目前的逻辑看好像写不出来

**Comment by GuhDoy** [comment]
只靠挂载确实做不到，你这个需求需要修改文件系统实现。
