### ISSUE TITLE
关于提示开关

### ISSUE THREAD

**Issue by ohdmire** [MaterialCleaner/MaterialCleaner#52]
能否加一个这个提示的开关，我的QQ一直在提示写入媒体文件，可能是用了模块的原因
![Screenshot_2023-03-22-01-52-01-697_me gm cleaner](https://user-images.githubusercontent.com/38505121/226700391-4404739a-78cf-40b2-a3fa-916caa56b651.jpg)

**Comment by Mubai-meng** [comment]
把你的规则发出来啊，是规则有问题才提示的

**Comment by ohdmire** [comment]
规则没啥问题吧
![Uploading Screenshot_2023-03-22-08-01-53-804_me.gm.cleaner.jpg…]()

**Comment by ohdmire** [comment]
![Screenshot_2023-03-22-08-01-53-804_me gm cleaner](https://user-images.githubusercontent.com/38505121/226769574-b97e9959-9f9f-4174-b4f6-aa7b94f55cf5.jpg)

**Comment by ohdmire** [comment]
解决了，卸载再安装一次就不提示了；应该是还原数据的时候出现的一些bug

**Comment by GuhDoy** [comment]
把QQ加入隐藏列表就不会提示了，这个提示与是否开启文件系统记录无关

**Comment by ohdmire** [comment]
好的，感谢
