### ISSUE TITLE
BUG: 仅在1.10.1版本下无法启动&服务超时

### ISSUE THREAD

**Issue by Windla** [MaterialCleaner/MaterialCleaner#53]
# 信息
Redmi 10x / MIUI12.0.7 / Android10
Magisk 25.2&Zygisk / 已授权root权限
Cleaner1.10.1 /  Cleaner Hooks v1.3

# 问题
在1.10.0(包括)版本前，可正常启动
在1.10.1版本下，出现“启动服务超时”提示

# 尝试解决
完全卸载APP及模块，重装无果

# 暂时方案
目前可行的方案是1.10.0配合Cleaner Hooks v1.3
(服务版本889+模块版本928)

# 问题日志
[Cleaner_1.10.1_2023年3月25日 12_08_19.log](https://github.com/MaterialCleaner/MaterialCleaner/files/11067972/Cleaner_1.10.1_2023.3.25.12_08_19.log)

# 其他
配置文件的备份什么时候出，重装没了（悲）

**Comment by GuhDoy** [comment]
感谢反馈，此问题将在下个版本修复
