### ISSUE TITLE
1.3版本hooks导致重启后界面卡死

### ISSUE THREAD

**Issue by 407711237** [MaterialCleaner/MaterialCleaner#54]
小米10S，MIUI14开发版，已经授权root，在alpha25.2和delta25.2面具尝试过，无论是否制定挂载规则，安装了hooks模块并启用，会导致开机解锁后系统界面卡死，只能禁用hooks才能正常开机，之前的版本hooks不会出现这种问题。

**Comment by GuhDoy** [comment]
[clr.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/11071594/clr.zip)
试一下测试版

**Comment by 407711237** [comment]
> [clr.zip](https://github.com/MaterialCleaner/MaterialCleaner/files/11071594/clr.zip) 试一下测试版
这个版本不会出现这个问题了

**Comment by 1human** [comment]
红米k30s  A13 Google商店版本 1.4.2 beta hook
依旧卡系统
