### ISSUE TITLE
删除Download文件夹下的文件偶现异常

### ISSUE THREAD

**Issue by CMDQ8575** [MaterialCleaner/MaterialCleaner#57]
如题，在多选删除download目录下的文件时，无论用re管理器还是via的下载管理里面的删除，都概率性出现掉sd卡挂载的情况，1.9或之前版本几秒后可以重新挂载上，1.10开始只能重启解决，又试了issue区里的那个beta版，问题依旧，而且magisk直接掉root，也是重启才能解决

**Comment by CMDQ8575** [comment]
> 
补充一点，如果删的东西包括目录，概率更高

**Comment by GuhDoy** [comment]
请提供挂载规则和异常信息截屏

**Comment by CMDQ8575** [comment]
规则参考如下，其余应用基本类似此规则（有少无多）。重定向应用有：百度网盘，酷安，闪电下载，微信，qq，wps。未对via与re管理器应用规则，未开启文件系统记录
![0](https://user-images.githubusercontent.com/35628468/228476080-62b0935a-f426-4035-8579-9ea2092ec208.jpg)
此次异常出现在re管理器删除download下几个下载的apk和appshare文件夹时出现。出现异常时手机sd卡无法挂载，且许多应用直接卡死和无响应，冷启动则黑屏。故此处使用另外的手机拍摄
![1](https://user-images.githubusercontent.com/35628468/228476517-0bbadbbe-5f5e-4c7d-9d75-205329fa4123.jpg)
![2](https://user-images.githubusercontent.com/35628468/228476528-68de6777-b49d-4d56-8f06-d70fdccae8d0.jpg)
![3](https://user-images.githubusercontent.com/35628468/228476540-8cc1ce15-fd32-4ae9-9ab5-31f3c38f4242.jpg)

**Comment by GuhDoy** [comment]
我不认为这是Cleaner造成的问题：
- Cleaner只会处理应用进程所在的命名空间，而不会对全局造成影响；
- 挂载是系统内核提供的功能，Cleaner只是使用，并不实现它；
- Cleaner只在应用启动时挂载，使用re文件管理器删除文件的时候，Cleaner不会做任何事。

当然，如果你可以抓取到有用的日志，欢迎继续反馈。

**Comment by CMDQ8575** [comment]
已经查出原因了。是冻结了下载管理程序的原因
