### ISSUE TITLE
mt管理器无法正常打开应用私有目录下的压缩包

### ISSUE THREAD

**Issue by Rarlya1** [MaterialCleaner/MaterialCleaner#59]
设备信息 redmi k60  MIUI14.0.11 A13
问题版本 cleaner 1.10及以上、hook 1.3及以上、mt管理器2.13.4

用mt管理器打开Android/data/内的压缩包文件大概率失败，无法解压无法预览，偶尔成功浏览也无法直接使用内部文件，但是可以在浏览状态解压到另一侧
该问题在cleaner1.9.3+hook1.3、单独使用cleaner1.10及以上时正常

[https://github.com/MaterialCleaner/MaterialCleaner/issues/54]()  连接内问题提供的hook1.4也存在该问题

以下是错误信息的截图
![Uploading IMG_20230405_235105.jpg…]()
![Uploading IMG_20230405_235214.jpg…]()
![Uploading IMG_20230405_235338.jpg…]()

**Comment by Rarlya1** [comment]
![IMG_20230405_235105](https://user-images.githubusercontent.com/118902587/230138318-d4866f86-50cd-485f-a286-d0534d7404f9.jpg)
![IMG_20230405_235214](https://user-images.githubusercontent.com/118902587/230138359-1408f1a0-8c30-4e50-9bca-a9664a4951c0.jpg)
![IMG_20230405_235338](https://user-images.githubusercontent.com/118902587/230138399-e89d0013-a236-4da6-ad92-14cf913928a3.jpg)

**Comment by Rarlya1** [comment]
[该问题在cleaner1.9.3+hook1.3、单独使用cleaner1.10及以上时正常]
这段话有误，是cleaner1.9.7+hook1.3及以上

**Comment by GuhDoy** [comment]
Is this a Bug report or a Feature request?

**Comment by Rarlya1** [comment]
> Is this a Bug report or a Feature request?

Bug report

**Comment by GuhDoy** [comment]
Please edit the title and provide more info (see Screenshots and Running environment section on the issue template).
