### ISSUE TITLE
开机后卡应用+系统

### ISSUE THREAD

**Issue by 1human** [MaterialCleaner/MaterialCleaner#61]
红米K30s 刷了类原生的 A13
最近几个版本的hooks（包括1.10.2+1.4.2hooks）刷入后重启，会有各种卡应用（无法读取图片等 ）、fc、系统重启之类的问题
我现在用的还是1.9.7+1.1hooks 没问题

**Comment by GuhDoy** [comment]
请不要删除标题中的 [Bug report] 或 [Feature request] 标签。
请按照模板提供相关信息，如截屏、日志等。
在满足以上要求之前，您不会得到任何议题相关的回复。
