### ISSUE TITLE
测试版与yc模块冲突导致微信视频部分消失

### ISSUE THREAD

**Issue by 1057143915** [MaterialCleaner/MaterialCleaner#62]
测试版与yc模块冲突导致微信视频部分消失 不知道怎么恢复视频

**Comment by GuhDoy** [comment]
请不要删除标题中的 [Bug report] 或 [Feature request] 标签。
请按照模板提供相关信息，如截屏、日志等。
在满足以上要求之前，您不会得到任何议题相关的回复。
