### ISSUE TITLE
安装cleaner模块后安装应用手机有概率重启

### ISSUE THREAD

**Issue by mytools1** [MaterialCleaner/MaterialCleaner#63]
重启后在data，cleaner模块文件里面会出现logs导致cleaner服务重启后运行不正常

**Comment by mytools1** [comment]
重启后模块自动关闭了

**Comment by mytools1** [comment]
![Screenshot_2023-05-18-20-32-03-62](https://github.com/MaterialCleaner/MaterialCleaner/assets/69223708/2575e08b-cf34-4b3a-98f4-ca825ca3fdf5)
安装了这些模块，不知道会不会有冲突，每次安装应用重启后，cleaner hooks模块会自动关闭，且会在/data/adb/modules/zygisk_cleanerhooks/生成一个logs文件。重启cleaner服务时提醒我有logs文件影响运行

**Comment by mytools1** [comment]
![Screenshot_2023-05-18-20-42-45-72_acfc761c91e7df8597f3db66ccc54ed6](https://github.com/MaterialCleaner/MaterialCleaner/assets/69223708/a4dd47d1-2517-4fcc-9a0b-592f5bc3d583)
这是重启后的截图

**Comment by mytools1** [comment]
https://wwjl.lanzoum.com/iMFPf0wism6h
这个是logs里的文件

**Comment by GuhDoy** [comment]
你的日志信息太少了，在开发者选项中把日志记录器缓冲区大小调到最大，然后复现问题后再上传日志

**Comment by GuhDoy** [comment]
由于无回应，标记为已完成

**Comment by Lehmaning** [comment]
确实，1.10版本之后在小米Android 11上占用高的离谱，经常性发热重启，1.10版本则是完全用不了，会直接反复重启。

**Comment by GuhDoy** [comment]
@Lehmaning 警告：如果遇到问题请创建新的议题或者讨论，而不是回复一个已关闭的议题。如果再犯，你会被ban
