### ISSUE TITLE
今日头条不生效

### ISSUE THREAD

**Issue by k650dg4d2** [MaterialCleaner/MaterialCleaner#8]
文件下载到了/storage/emulated/0/news_article/这个文件夹，重定向后还是下载到了这个文件夹

**Comment by GuhDoy** [comment]
试一下这样编写规则

![Screenshot_2022-06-04-15-01-25-000_me.gm.cleaner.jpg](https://user-images.githubusercontent.com/46047320/171988638-2edcfca7-836c-4256-9a07-c668fb43080c.jpg)

**Comment by k650dg4d2** [comment]
> 试一下这样编写规则
> 
> ![Screenshot_2022-06-04-15-01-25-000_me.gm.cleaner.jpg](https://user-images.githubusercontent.com/46047320/171988638-2edcfca7-836c-4256-9a07-c668fb43080c.jpg)

原来是这样，我把来源和目标搞反了。我以为来源是图片的来源，目标是要移动到的目标文件夹。
