### ISSUE TITLE
[Bug report] 服务启动后会自动关闭

### ISSUE THREAD

**Issue by mromm** [MaterialCleaner/MaterialCleaner#83]
- Device: [小米13Ultra]
 - OS: [Android 13_MIUI14]
 - Cleaner Version [1.10.4]
 - Cleaner Hooks Version [1.6]
 - MPM Version [Not Installed]

[Cleaner_1.10.4_2023年7月5日 11_08_14.log](https://github.com/MaterialCleaner/MaterialCleaner/files/11953721/Cleaner_1.10.4_2023.7.5.11_08_14.log)

打开开机启动服务选项，进入软件时情况一样，使用Zygisk on KernelSU加载的模块

**Comment by mromm** [comment]
打开开机启动服务选项，进入软件时情况一样

**Comment by GuhDoy** [comment]
这是由于你没有使用由应用生成的以下文件导致的：
/data/user/0/me.gm.cleaner/shared_prefs/__androidx_security_crypto_encrypted_pref__.xml
/data/user_de/0/me.gm.cleaner/shared_prefs/__androidx_security_crypto_encrypted_pref__.xml
例如在更换设备或者卸载重装后仍然使用之前生成的文件，或者手动修改过这些文件。
解决方法就是把它们删掉，让应用重新生成。
