### ISSUE TITLE
[Bug report] 文件系统记录不显示最新一条记录

### ISSUE THREAD

**Issue by 821938089** [MaterialCleaner/MaterialCleaner#84]
You have been warned ⚠️⚠️⚠️Any issues that ignore this template will be closed directly!!!

If your issue is not easily reproducible on other devices, please provide as much detail as possible and confirm that you know how to grab helpful logs.

You may get asked to provide further information. If you are unwilling to engage further in the first place, you are better off refraining from asking the question, as this will only waste our time.

Don't be under the illusion that we can fix issues with incomplete information. Incomplete information is not only of no help in solving the problem but even makes people doubt whether the problem exists.

你已经被警告⚠️⚠️⚠️任何无视此模板的议题，都会被直接关闭！！！

如果您提出的不是很容易在其他设备复现的问题，请务必尽可能详细地提供信息，并确认您知道如何抓取有用的日志。

您可能被要求进一步补充信息。如果您从一开始就不打算进一步互动，那还不如不要提出问题，这只是在浪费大家的时间。

不要幻想我们能在信息不完整的情况下解决问题。不完整的信息不仅对于解决问题没有任何帮助，甚至会让人怀疑问题是否真实存在。

***

**Describe the bug**
文件系统记录不显示最新一条记录

**To Reproduce**
1. 随便打开一些app记录文件操作
2. 进入Cleaner的文件系统记录
3. 点右上角精简记录，显示有8条，但是实际只显示了7条

**Screenshots**

![photo](https://github.com/MaterialCleaner/MaterialCleaner/assets/8674809/e6cb8adc-7abc-4ae9-824a-4c3c2634afb4)

**Running environment (please complete the following information):**
 - Device: 红米K60
 - OS: 安卓13
 - Cleaner Version 1.10.5
 - Cleaner Hooks Version 1.6.1
 - MPM Version 无

**Logs**
app里没找到哪里可以导出日志

**Additional context**
还有另外一个问题，从app右上角联系里面进入github反馈是不会使用这个问题模板的

**Comment by GuhDoy** [comment]
感谢反馈，Play 商店的下个正式版（1.10.5 1198）会修复此问题。
