### ISSUE TITLE
[Feature request] 捐赠功能和清理功能优化

### ISSUE THREAD

**Issue by cxyzzz** [MaterialCleaner/MaterialCleaner#85]
- 捐赠功能能否增加国内渠道支持？（如支付宝、微信、亦或者是play商店兑换码）。play商店支付比较麻烦。
- 缓存、日志等清理项目扫描完成后按应用划分列表，这样比较清晰，有些应用不需要清理很快就能进行排除。

**Comment by chengnan049** [comment]
捐赠功能实现的比较麻烦，因为国内不这么允许，可以私信开发者获取

**Comment by GuhDoy** [comment]
- 清理功能将来会做非常大的加强。支持国内购买渠道我打算等清理功能完成之后再尝试，预计需要的时间还比较久。
- 清理扫描结果支持按应用名搜索，另外由于路径包含包名，因此也可以搜索包名。如果有应用不需要清理，可以在设置中将它们的数据目录添加到不扫描，这样扫描时会跳过设定的目录，既能实现你的需求，又能减少扫描时间。如果你是出于使用习惯的原因需要按应用划分列表，这个也得等到清理功能完成之后再考虑，因为将来的使用方式会很不一样。

另外两个Feature request建议开两个issue ^_^
