### ISSUE TITLE
[Feature request] 支持设置扫描缓存文件大小或者时间

### ISSUE THREAD

**Issue by Vstory** [MaterialCleaner/MaterialCleaner#89]
**Is your feature request related to a problem? Please describe.**
对应用开启存储空间隔离后，支持在页面对应用设置缓存时间或者大小。
例如，设置应用不在共享空间保存有用数据后，挂载路径为/storage/emulated/0/Android/data/com.Example/cache
在 cache 挂在 而不是 files 时，增加该设置，减少清理缓存时，短时效有用的缓存文件被清理。长期缓存，可以正常被清理。

时间或者大小设置后，在主界面扫描开始时，将遵守该规则，满足规则的缓存文件不做清理。

**Describe the solution you'd like**
无

**Describe alternatives you've considered**

**Additional context**

**Comment by GuhDoy** [comment]
So what's the solution you'd like?

**Comment by GuhDoy** [comment]
由于无回应关闭
