### ISSUE TITLE
这个好像会重命名啊，我感觉没必要啊

### ISSUE THREAD

**Issue by k650dg4d2** [MaterialCleaner/MaterialCleaner#9]
![IMG_20220607_053820](https://user-images.githubusercontent.com/32454224/172253615-06a8e619-b04a-45b4-8242-db9743645636.jpg)
如图所示，感觉多此一举啊，原来名字挺好的。现在重命名就变成一串数字了。可以加一个保存原来名称的设置嘛

**Comment by GuhDoy** [comment]
不知道你在说什么。。。

**Comment by k650dg4d2** [comment]
> 

是telegram自己的问题，下载下来不是源文件名，必须要点保存到下载文件夹才会使显示的名称。我的问题
