### ISSUE TITLE
[Bug report] 显示异常但是mountinfo有

### ISSUE THREAD

**Issue by mio-19** [MaterialCleaner/MaterialCleaner#93]
You have been warned ⚠️⚠️⚠️Any issues that ignore this template will be closed directly!!!

If your issue is not easily reproducible on other devices, please provide as much detail as possible and confirm that you know how to grab helpful logs.

You may get asked to provide further information. If you are unwilling to engage further in the first place, you are better off refraining from asking the question, as this will only waste our time.

Don't be under the illusion that we can fix issues with incomplete information. Incomplete information is not only of no help in solving the problem but even makes people doubt whether the problem exists.

你已经被警告⚠️⚠️⚠️任何无视此模板的议题，都会被直接关闭！！！

如果您提出的不是很容易在其他设备复现的问题，请务必尽可能详细地提供信息，并确认您知道如何抓取有用的日志。

您可能被要求进一步补充信息。如果您从一开始就不打算进一步互动，那还不如不要提出问题，这只是在浪费大家的时间。

不要幻想我们能在信息不完整的情况下解决问题。不完整的信息不仅对于解决问题没有任何帮助，甚至会让人怀疑问题是否真实存在。

***

**Describe the bug**
如题

**To Reproduce**
1. 设置一个非常标准的重定向规则

**Screenshots**
![Screenshot_20230922_154606_Termux](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/c99681dd-d04b-44b0-b3f5-bf7010340ca9)
![Screenshot_20230922_154508_Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/e87c9984-ff99-4c58-9d37-19db71784f9b)

Add a screenshot of your mount rules if your issue is about storage redirect feature.

**Running environment (please complete the following information):**
 - Device: [e.g. Pixel 6] Samsung S21Ultra
 - OS: [e.g. Android 8.1] 13
 - Cleaner Version [e.g. 1.6] 1.10.6
 - Cleaner Hooks Version [e.g. Not Installed/1.4] 1.7.4
 - MPM Version [e.g. Not Installed/beta4, installed but not activated/beta4, activated with LSPosed] no

**Logs**
Where can I get logs?

**Additional context**

**Comment by GuhDoy** [comment]
你发的截屏并不完整。请上传完整的mountinfo文件和完整的挂载规则截屏，这不会导致你的隐私泄露。

**Comment by mio-19** [comment]
![Screenshot_20230922_160410_Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/d4a10410-7d8a-473b-9198-a0506c2189ee)
![Screenshot_20230922_160545_Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/facbcbf1-17a2-4165-8d08-01dabf1c47ff)
手机github网页版没有上传文本文件按钮我看看客户端

**Comment by mio-19** [comment]
[mtinf.txt](https://github.com/MaterialCleaner/MaterialCleaner/files/12698456/mtinf.txt)
![Screenshot_20230922_160915_Termux](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/47976174-29f9-494f-95d2-cd38ddf2b48f)

**Comment by GuhDoy** [comment]
无法复现。
我将挂载规则设为与你的截屏一致，然后将检查代码改为打开你提供的mountinfo文件，并没有出现问题。
![Screenshot_2023-09-22-16-28-03-035_me gm cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/46047320/ed15c3df-7c17-448d-8814-5f2703d5bfaf)

**Comment by mio-19** [comment]
在我的设备上所有app都出现了类似的问题。 Cleaner 的日志文件要去哪里找
![Screenshot_20230922_163251_Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/4aa64955-de32-421f-b804-514c35b98213)

**Comment by GuhDoy** [comment]
重新挂载问题通常不是由Cleaner引起，因此没有日志

**Comment by mio-19** [comment]
重新挂载问题的提示会只取决于mountinfo的内容吗 还是有一些其他情况也会出现这种提示

> 无法复现。 我将挂载规则设为与你的截屏一致，然后将检查代码改为打开你提供的mountinfo文件，并没有出现问题。

**Comment by GuhDoy** [comment]
重新挂载异常是 挂载过程没有出现任何异常的情况下，mountinfo与挂载规则设置不一致

**Comment by mio-19** [comment]
WSA也有类似的情况
![image](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/224c33e0-5b7d-4d2a-810f-300a5525e6d1)
mountinfo:
[meituan.txt](https://github.com/MaterialCleaner/MaterialCleaner/files/12701418/meituan.txt)
![image](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/6ea1147d-7718-430f-b684-3885ff40899d)


WSA_2308.40000.1.0_x64_Release-Nightly-with-magisk-26.3(26300)-stable-MindTheGapps-13.0

Android 13 WSA 2308

  用了MagiskOnWSA https://github.com/LSPosed/MagiskOnWSALocal/pull/620

**Comment by mio-19** [comment]
> 重新挂载异常是 挂载过程没有出现任何异常的情况下，mountinfo与挂载规则设置不一致

或许是某些未知的原因导致Cleaner检查mountinfo时出现错误

**Comment by GuhDoy** [comment]
我想起来了正式版是有个地方会导致这个问题，之前在安卓14的avd上复现过。用play的开放式测试版本试一下吧

**Comment by mio-19** [comment]
> 我想起来了正式版是有个地方会导致这个问题，之前在安卓14的avd上复现过。用play的开放式测试版本试一下吧

beta版本没有问题。
