### ISSUE TITLE
[Bug report] 错误的提示：Wechat将图片保存到了中间含有“(invalid)"的路径

### ISSUE THREAD

**Issue by mio-19** [MaterialCleaner/MaterialCleaner#94]
You have been warned ⚠️⚠️⚠️Any issues that ignore this template will be closed directly!!!

If your issue is not easily reproducible on other devices, please provide as much detail as possible and confirm that you know how to grab helpful logs.

You may get asked to provide further information. If you are unwilling to engage further in the first place, you are better off refraining from asking the question, as this will only waste our time.

Don't be under the illusion that we can fix issues with incomplete information. Incomplete information is not only of no help in solving the problem but even makes people doubt whether the problem exists.

你已经被警告⚠️⚠️⚠️任何无视此模板的议题，都会被直接关闭！！！

如果您提出的不是很容易在其他设备复现的问题，请务必尽可能详细地提供信息，并确认您知道如何抓取有用的日志。

您可能被要求进一步补充信息。如果您从一开始就不打算进一步互动，那还不如不要提出问题，这只是在浪费大家的时间。

不要幻想我们能在信息不完整的情况下解决问题。不完整的信息不仅对于解决问题没有任何帮助，甚至会让人怀疑问题是否真实存在。

***

**Describe the bug**
如题。图片保存到了应该保存的地方 Pictures/WeChat 。只有错误的警告是bug

**To Reproduce**

在微信中保存一张聊天中的图片。
规则：
![Screenshot_20230924_191720_Material Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/80da37b3-226c-48a9-a7be-3e3cb2d3a6cf)

**Screenshots**
Add a screenshot of your mount rules if your issue is about storage redirect feature.
![Screenshot_20230924_191401_WeChat](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/02be8a66-bbd1-4518-a057-2473c6c52726)

**Running environment (please complete the following information):**
 - Device: [e.g. Pixel 6] SamsungS21Ultra
 - OS: [e.g. Android 8.1] Android13
 - Cleaner Version [e.g. 1.6] Play Beta版本
 - Cleaner Hooks Version [e.g. Not Installed/1.4] 1.7.4
 - MPM Version [e.g. Not Installed/beta4, installed but not activated/beta4, activated with LSPosed] Not installed

**Logs**

**Additional context**

**Comment by GuhDoy** [comment]
这说明getCanonicalPath没有返回正确的路径，这个函数是由文件系统实现的，因此这是文件系统的bug，与Cleaner无关。另外，通知中的路径是经过转换后的路径，getCanonicalPath原本返回的路径是什么免费版无法查看。

**Comment by mio-19** [comment]
这也可以是getCanonicalPath没有被输入正确的路径

**Comment by GuhDoy** [comment]
输入路径的获取方法是[开源](https://github.com/MaterialCleaner/Media-Provider-Manager/blob/main/app/src/main/java/me/gm/cleaner/plugin/xposed/hooker/InsertHooker.kt)的
