### ISSUE TITLE
[Feature request] 双开/多用户（/storage/emulated/非0)的支持

### ISSUE THREAD

**Issue by mio-19** [MaterialCleaner/MaterialCleaner#95]
**Is your feature request related to a problem? Please describe.**

三星/小米等手机的rom用多用户实现了双开。想对双开的应用增加重定向规则

**Describe the solution you'd like**
在后端支持 /storage/emulated/非0 的规则
在ui服务设置中将其他用户的app分开显示 显示为“应用 （用户id）”

**Describe alternatives you've considered**

**Additional context**

**Comment by GuhDoy** [comment]
很早之前就已经支持了多用户，可以将多用户的文件保存在对应用户的存储空间。不过如果你想要把多用户的文件保存在主用户的存储空间，目前还没有支持。
另外由于 Cleaner 服务缺少收入，目前在我 TODO 中的 2 个改进和 2 个修复已被迫中止，接下来的工作重心会放在清理功能上。在有足够的用户和收入前，我不会再对 Cleaner 服务做任何影响不够大并且有一天以上工作量的改进或修复。

**Comment by GuhDoy** [comment]
由于我失去了继续开发的热情，因此废弃此计划
