### ISSUE TITLE
[Bug report] 未声明储存权限的app保存图片出现与实际行为不符的警告：受储存重定向影响...

### ISSUE THREAD

**Issue by mio-19** [MaterialCleaner/MaterialCleaner#96]
You have been warned ⚠️⚠️⚠️Any issues that ignore this template will be closed directly!!!

If your issue is not easily reproducible on other devices, please provide as much detail as possible and confirm that you know how to grab helpful logs.

You may get asked to provide further information. If you are unwilling to engage further in the first place, you are better off refraining from asking the question, as this will only waste our time.

Don't be under the illusion that we can fix issues with incomplete information. Incomplete information is not only of no help in solving the problem but even makes people doubt whether the problem exists.

你已经被警告⚠️⚠️⚠️任何无视此模板的议题，都会被直接关闭！！！

如果您提出的不是很容易在其他设备复现的问题，请务必尽可能详细地提供信息，并确认您知道如何抓取有用的日志。

您可能被要求进一步补充信息。如果您从一开始就不打算进一步互动，那还不如不要提出问题，这只是在浪费大家的时间。

不要幻想我们能在信息不完整的情况下解决问题。不完整的信息不仅对于解决问题没有任何帮助，甚至会让人怀疑问题是否真实存在。

***

**Describe the bug**
显示了一个错误的警告，文件实际存在了DCIM。

或者重定向未按照预期的方式工作？ 不清楚这种情况下Cleaner设计的行为是什么

**To Reproduce**

小红书保存图片

**Screenshots**
Add a screenshot of your mount rules if your issue is about storage redirect feature.
![Screenshot_20231003_021431_Gallery](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/89d4126d-5783-4084-be02-b526fbebf836)
![Screenshot_20231003_021645_Material Cleaner](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/9864a510-4ea8-49a7-bb6d-847e85a08a3c)
![Screenshot_20231003_021926_My Files](https://github.com/MaterialCleaner/MaterialCleaner/assets/57285379/7e951910-237f-449b-9e87-918f71fcfaa7)

**Running environment (please complete the following information):**
 - Device: [e.g. Pixel 6] Samsung S21 Ultra
 - OS: [e.g. Android 8.1] 13
 - Cleaner Version [e.g. 1.6] 1.10.6 Google Play Beta
 - Cleaner Hooks Version [e.g. Not Installed/1.4] 1.7.4
 - MPM Version [e.g. Not Installed/beta4, installed but not activated/beta4, activated with LSPosed] beta10 lsposed

**Logs**
Logs are a must if the bug is not reproducible on all my running environments! If you don't provide logs in this case, the issue will be closed, and you may get banned!

**Additional context**

**Comment by GuhDoy** [comment]
这是通过媒体存储保存的文件，在不修改系统行为的情况下，将插入路径修改为私有目录会导致文件丢失，非常危险

**Comment by mio-19** [comment]
期望的行为是

+ 弹出了警告并且确实保存到了私有目录，或者
+ 不弹出保存到了私有目录的警告

**Comment by GuhDoy** [comment]
首先这样做是在砍功能。
然后媒体存储这部分是没有完美的解决方案的，总有人要做妥协。

- 把媒体存储的概念完全砍掉的方案，会导致不能发挥出媒体存储API降低管理难度的优势：
  - 媒体存储能按MimeType拦截，利用这个特性解决“拉屎”问题非常简单，你只需要设置一个像这样的模板 ，然后把拉屎的应用加进去就行了。如果使用挂载规则，设置会更复杂而且有副作用。
![IMG_20231003_150342](https://github.com/MaterialCleaner/MaterialCleaner/assets/46047320/4f63b478-1f51-45cb-ae46-ea58d7e62c85)
  - 挂载是读取写入同时授权，媒体存储可以不同时授权。

- 不处理媒体存储的方案：
  - 一些用户有重定向这部分文件的需求。
  - 你提出的方案很有可能被用户认为“侧漏”，因为文件没有保存在预期（按照他们设置的挂载规则）的位置。

- 在用户不知情的情况下修改系统行为我认为是不可接受的，这也是很多国产系统被开发者喷的原因。

目前的方案已经是我觉得最好的了，不过如果你有更好的方案，欢迎提出。

**Comment by GuhDoy** [comment]
那么具体应该如何修改？“受存储重定向影响，小红书的媒体文件侧漏了”？

**Comment by mio-19** [comment]
小红书使用了媒体储存插入文件，未受到存储重定向规则限制，保存到了公有目录/storage/emulated/0/DCIM/a.jpg

**Comment by GuhDoy** [comment]
此问题已修复
