### ISSUE TITLE
[Bug report] 未设置Download目录重定向，则应用无法下载

### ISSUE THREAD

**Issue by qanyue** [MaterialCleaner/MaterialCleaner#98]
You have been warned ⚠️⚠️⚠️Any issues that ignore this template will be closed directly!!!

If your issue is not easily reproducible on other devices, please provide as much detail as possible and confirm that you know how to grab helpful logs.

You may get asked to provide further information. If you are unwilling to engage further in the first place, you are better off refraining from asking the question, as this will only waste our time.

Don't be under the illusion that we can fix issues with incomplete information. Incomplete information is not only of no help in solving the problem but even makes people doubt whether the problem exists.

你已经被警告⚠️⚠️⚠️任何无视此模板的议题，都会被直接关闭！！！

如果您提出的不是很容易在其他设备复现的问题，请务必尽可能详细地提供信息，并确认您知道如何抓取有用的日志。

您可能被要求进一步补充信息。如果您从一开始就不打算进一步互动，那还不如不要提出问题，这只是在浪费大家的时间。

不要幻想我们能在信息不完整的情况下解决问题。不完整的信息不仅对于解决问题没有任何帮助，甚至会让人怀疑问题是否真实存在。

***

**Describe the bug**
## 在只设置隔离的情况下，应用下载会显示中断（不知道为什么图片这么大，可以缩小网页）
![2f0d9a4892fe1048baedff0d0854315](https://github.com/MaterialCleaner/MaterialCleaner/assets/55617091/d8b35b2d-818f-44da-976d-52a9c53f35d5)
## 下载出错提示
![74da063323c46d3af116cfa76f91c74](https://github.com/MaterialCleaner/MaterialCleaner/assets/55617091/21616ac0-3c05-4131-ba53-04256a09aa0c)
## 而在添加下载目录重定向后可以下载
![7520be9fb71ad5ce8e45a725d57f14b](https://github.com/MaterialCleaner/MaterialCleaner/assets/55617091/f657c31e-195c-4b6a-bfca-0f502307f079)

## 然后也没有重定向提示。

**To Reproduce**

**Screenshots**
Add a screenshot of your mount rules if your issue is about storage redirect feature.

**Running environment (please complete the following information):**
 - Device: [Mi 10]
 - OS: [Android 13]
 - Cleaner Version [1.6]
 - Cleaner Hooks Version [1.7.4]
 - MPM Version [activated with LSPosed]

**Logs**
Logs are a must if the bug is not reproducible on all my running environments! If you don't provide logs in this case, the issue will be closed, and you may get banned!
[logcat_33_2023年10月6日 11_54_29.log](https://github.com/MaterialCleaner/MaterialCleaner/files/12826779/logcat_33_2023.10.6.11_54_29.log)

**Additional context**

**Comment by GuhDoy** [comment]
我不明白什么是隔离空间，我也没用过并且在线规则里也没有CCtalk这个应用

**Comment by GuhDoy** [comment]
存储重定向提示对话框是在应用请求系统更新媒体库时弹出，不弹出就说明应用没有请求系统更新媒体库
