### ISSUE TITLE
系统文件记录打开闪退

### ISSUE THREAD

**Issue by Gemini-Shan** [MaterialCleaner/MaterialCleaner#99]
手机型号：OPPO Find X6pro
系统：ColorOS 13.1
质感清理已购买，模块已刷好。能重定向文件，就是系统文件记录这个不能打开，一打开就闪退。请求帮助，谢谢！

**Comment by GuhDoy** [comment]
您好，这个是oppo系统修改了系统框架数据库导致的。由于质感清理使用room（对访问系统框架数据库做了封装），我们很难解决此问题，因为这意味着所有数据库相关的代码全部重做，我们无法为手机厂商的错误付出如此大代价。

如果您认为此功能非常重要，建议您回退旧版系统、切换其它系统或者升级到color os14。
